### ISSUE TITLE
Push.ino example issue with DatabaseSession Session("S01")

### ISSUE THREAD

**Issue by kalu1** [mobizt/AsyncFirebaseClient#1]
Hi it seems in examples/Database/Async/Push/Push.ino is bug.

During building the code there is error, see below.
After renamed Session in DatabaseSession Session("S01"); and also in push comands there is no error and it also works.
Thanks
Lukas

src/main.cpp:145:24: error: 'DatabaseSession session' redeclared as different kind of symbol
 DatabaseSession session("S01");
                        ^
In file included from lib/AsyncFirebaseClient-main/src/core/AppBase.h:29,
                 from lib/AsyncFirebaseClient-main/src/AsyncFirebaseClient.h:33,
                 from src/main.cpp:124:
lib/AsyncFirebaseClient-main/src/database/Database.h:38:37: note: previous declaration 'using session = struct request_session_data'
 using session = request_session_data;
                                     ^
src/main.cpp: In function 'void setup()':
src/main.cpp:192:46: error: expected primary-expression before ',' token
     database.push("/test/int", 12345, session, appCB);
                                              ^
src/main.cpp:195:46: error: expected primary-expression before ',' token
     database.push("/test/bool", true, session, appCB);
                                              ^
src/main.cpp:198:51: error: expected primary-expression before ',' token
     database.push("/test/string", "hello", session, appCB);
                                                   ^
src/main.cpp:201:46: error: expected primary-expression before ',' token
     database.push("/test/json", json, session, appCB);
                                              ^
src/main.cpp:204:44: error: expected primary-expression before ',' token
     database.push("/test/arr", arr, session, appCB);
                                            ^
src/main.cpp:207:60: error: expected primary-expression before ',' token
     database.push<float>("/test/float", 123.456, 2, session, appCB);
                                                            ^
src/main.cpp:210:65: error: expected primary-expression before ',' token
     database.push<double>("/test/double", 1234.56789, 4, session, appCB);
                                                                 ^
*** [.pio\build\esp32doit-devkit-v1\src\main.cpp.o] Error 1

**Comment by mobizt** [comment]
Thanks for reporting this issue.

Now it was fixed, please update library.
