### ISSUE TITLE
Starting wifi in c then running generic 

### ISSUE THREAD

**Issue by ThatBigPrint** [mobizt/AsyncFirebaseClient#2]
Hi im having issues... I'm starting wifi with my own c lib I then pass my wifi connected state to the generic network example vs the original arduino esp wifi config step wifi is available in the c side but the arduino side it's not? Is this lib reliant on a deeper level of arduino wifi? 

Similar issue when using the "main client library" as a work around I did provisioning in arduino but now I need to use esp mesh functions in c

**Comment by mobizt** [comment]
Library does nothing with the network, it depends on the status set by user in the callback in case of generic network.

As you will see,
https://github.com/mobizt/AsyncFirebaseClient/blob/24f7b834c92c63efd4ea69e36c531c14e7219513/examples/App/NetworkInterfaces/GenericNetwork/GenericNetwork.ino#L130
the status obtained from core WiFi library function.

**Comment by ThatBigPrint** [comment]
I provide a bool true for that status once wifi in the c side is able to get ip... It aperars to be failing at line 90

**Comment by ThatBigPrint** [comment]
And for the older client, it just didn't get past the Firebase.begin

**Comment by mobizt** [comment]
I have no idea with your issue.

I assume that you are using ESP32.

The `esp-idf` `esp_wifi` functions called in [core WiFi library](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/src/WiFi.cpp) internally.

**Comment by mobizt** [comment]
> And for the older client, it just didn't get past the Firebase.begin

You should update your Arduino core SDK as there is a bug in WiFi library if `WiFi.autoreconnect` was called internally in this library via `Firebase.reconnectNetwork`.

Or set this option with false or remove this line from your code.
`Firebase.reconnectNetwork(false);`

**Comment by ThatBigPrint** [comment]
I'm using the mesh lite wifi init in this it's basically the same as the standard method below

ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_STA) );
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &wifi_config) );
    ESP_ERROR_CHECK(esp_wifi_start() );

https://github.com/espressif/esp-mesh-lite/blob/master/examples/mesh_local_control/main/local_control.c

**Comment by ThatBigPrint** [comment]
> > And for the older client, it just didn't get past the Firebase.begin
> 
> You should update your Arduino core SDK as there is a bug in WiFi library if `WiFi.autoreconnect` was called internally in this library via `Firebase.reconnectNetwork`.
> 
> Or set this option with false or remove this line from your code. `Firebase.reconnectNetwork(false);`

I did both remove and set to false to no avail

**Comment by mobizt** [comment]
If you try to use WiFi with mesh, check your WiFi mode and internet connection instead.

It's not related to the library in any way.

**Comment by mobizt** [comment]
You are using esp-idf library in Arduino framework which is not 100% compatibility.

There is some WiFi mesh library available in Arduino e.g. [painlessMesh](https://github.com/gmag11/painlessMesh) which active development on GitLab.
